### ISSUE TITLE
Examples Do Not Build on macOS 15.1.1 with .NET 9.0.100

### ISSUE THREAD

**Issue by TheSameCat2** [HexaEngine/Hexa.NET.ImGui#29]
## What I Found

I am very interested in this project, and cloned the Master branch, as well as downloading the recent Release zip file. In both cases, I attempted to build several of the example projects using ```dotnet build``` and received dozens of the following errors:

```
/Hexa.NET.ImGui-2.2.2/ExampleOpenGL3/ImGuiOpenGL3Renderer.cs(677,121): error CS0120: An object reference is required for the non-static field, method, or property "GL.BindBuffer(GLBufferTargetARB, uint)"
```
All of the other errors were also CS0120 errors, and all pertaining to OpenGL.

## What I Have Tried

Not much I admit. I did try running ```dotnet restore``` just in case something wasn't getting pulled down from NuGet.

## Summary

I'm not complaining much, as this is Open Source and I know ya'll probably hear nothing but complaints, but I was wondering if this was a known issue, or if something I'm doing is especially boneheaded (in which case I'm hoping a kind soul will point me in the right direction).

I'm no OpenGL expert, just a desktop app developer looking for a new cross platform GUI toolkit.
I am happy to follow up with whatever details would be relevant to the knowledgable devs if it's a bug.
Thanks for your valuable time.

**Comment by JunaMeinhold** [comment]
Hi, it's probably just that I updated the nuget packages and forgot about checking if it compiles (because it takes ages). Will fix later this day

**Comment by JunaMeinhold** [comment]
And if you want a cross platform GUI toolkit i recommend my "UI Framework" which handles all the backends stuff for you and simplifies creating widgets
https://github.com/HexaEngine/Hexa.NET.KittyUI

**Comment by TheSameCat2** [comment]
Thank you so much! If you want someone to test compile on an Intel mac, let me know. 
Giving the KittyUI repo a look now!

**Comment by JunaMeinhold** [comment]
Okay i fixed the compiler errors. Also thanks for the donation <3.
